# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: webtp3/docker:alpha

pipelines:
  default:
    - step:
        image: webtp3/docker:alpha
        caches:
          - composer
        script:
          - apt-get update && apt-get upgrade -y
          - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          - php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          - php composer-setup.php
          - php -r "unlink('composer-setup.php');"
          - php composer.phar install create-project web-tp3/tp3_installer:alpha

    - step:
        name: Deploy to staging
        image: php:7.1.1
        deployment: staging
        trigger: manual
        script:
          - python deploy.py staging
    - step:
        name: Deploy to production
        image: aneitayang/aws-cli:1.0
        deployment: production
        trigger: manual
        script:
          - python deploy.py prod