# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: 7.1-apache

pipelines:
  default:
    - step:
        image: php:7.1.1
        caches:
          - composer
        script:
          - add-apt-repository ppa:ondrej/php
          - apt-get update && apt-get install -y unzip  php7.0-gd php7.0-zip php7.0-mysqli php7.0-soap php7.0-pcntl
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - composer require web-tp3/tp3_installer
          - composer update --dev
    - step:
        name: Deploy to test
        image: php:7.1.1
        deployment: test
        script:
          - mkdir -p ~/.ssh
          - cat my_known_hosts >> ~/.ssh/known_hosts
          - (umask  077 ; echo $myKey | base64 --decode > ~/.ssh/id_rsa)
          - ssh $user@$srv 'echo "connected to `host` as $USER"
          - cd ../../web
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - composer require web-tp3/tp3_installer
          - composer update --dev
    - step:
        name: Deploy to staging
        image: php:7.1.1
        deployment: staging
        trigger: manual
        script:
          - python deploy.py staging
    - step:
        name: Deploy to production
        image: aneitayang/aws-cli:1.0
        deployment: production
        trigger: manual
        script:
          - python deploy.py prod