# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: webtp3/docker:alpha

pipelines:
  default:
    - step:
        image: webtp3/docker:8.x-dev
        caches:
          - composer
        script:
          - apt-get update && apt-get upgrade -y
          - cd /var/www/
          - composer --dev --stability=dev create-project web-tp3/tp3_installer:dev-8.x-dev html
          - cd html
          # start testing
          - php vendor/phpunit/phpunit/phpunit --configuration web/typo3conf/ext/cag_tests/Tests/Build/UnitTests.xml --teamcity
          - php vendor/phpunit/phpunit/phpunit --configuration web/typo3conf/ext/cag_tests/Tests/Build/UnitTestsDeprecated.xml --teamcity
          - php vendor/phpunit/phpunit/phpunit --configuration web/typo3conf/ext/cag_tests/Tests/Build/FunctionalTests.xml --teamcity
          - mkdir -p web/typo3temp/var/tests
          - ./bin/chromedriver --url-base=/wd/hub >/dev/null 2>&1 &
          - php -S 0.0.0.0:8000 >/dev/null 2>&1 &
          - sleep 3;
          - typo3DatabaseName='typo3' typo3DatabaseHost='localhost' typo3DatabaseUsername='root' typo3DatabasePassword='pw' vendor/codeception/codeception/codecept run Acceptance -c web/typo3conf/ext/cag_tests/Tests/Build/AcceptanceTests.yml


    - step:
        name: Deploy to staging
        image: php:7.1.1
        deployment: staging
        trigger: manual
        script:
          - python deploy.py staging
    - step:
        name: Deploy to production
        image: aneitayang/aws-cli:1.0
        deployment: production
        trigger: manual
        script:
          - python deploy.py prod